version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\urfave\gfmrun

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.11
  GFMRUN_DEBUG: 1

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;c:\MinGW\bin;%PATH%
  - go version
  - go env
  - go get -v -t ./...
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - golangci-lint run

build_script:
  - mingw32-make
