name: Test and Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    name: Test GFMRUN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
          
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ^3.10

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Setup ZSH
        run: sudo apt-get install -y zsh

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2

      - name: Run Test Suite
        run: make all

      - name: Build Binary
        run: make build

      - name: Create Release
        id: create_release
        if: startswith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./gfmrun-linux-*
            ./gfmrun-darwin-*
            ./gfmrun-windows-*
