name: Test and Build

on:
  pull_request:
    branches:
      master
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test GFMRUN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Run Linter
        run: golangci-lint run

      - name: Run Test Suite
        run: make all

      - name: Build Binary
        if: success() && contains(github.ref, 'v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
